input=./excels
output=./generated/bytes/client
target=client
convertFormat=bin
package=DataConfig
recursive=true
sheet=
overwrite=true
checkRef=true
selfDescribing=false
logLevel=info
logFormat=text
logFile=./log/convert-client-config.log