input=./excels
output=./generated/bytes/all
target=both
convertFormat=bin
package=DataConfig
recursive=true
sheet=
overwrite=true
checkRef=true
selfDescribing=false
logLevel=info
logFormat=text
logFile=./log/convert-all-config.log