input=./generated/bytes/server
schemaInput=./excels
output=./decoded/server
target=server
decodeFormat=json
recursive=true
print=true
printMode=verbose
sheet=
overwrite=true
checkRef=true
selfDescribing=false
logLevel=info
logFormat=text
logFile=./log/decode-server-config.log