input=./generated/bytes/client
schemaInput=./excels
output=./decoded/client
target=client
decodeFormat=json
recursive=true
print=true
printMode=verbose
sheet=
overwrite=true
checkRef=true
selfDescribing=false
logLevel=info
logFormat=text
logFile=./log/decode-client-config.log