input=./generated/bytes/all
schemaInput=./excels
output=./decoded/all
target=both
decodeFormat=json
recursive=true
print=true
printMode=verbose
sheet=
overwrite=true
checkRef=true
selfDescribing=false
logLevel=info
logFormat=text
logFile=./log/decode-all-config.log